### ISSUE TITLE
Provide guidance to create configuration file

### ISSUE THREAD

**Issue by alexlandpro** [gopinath-langote/1build#79]
Display guiding messages on
- pip installation finished
- 1build is ran and configuration file does not exist

Provide a simple example of configuration file so that the user does not have to to README

**Comment by Ritabrata-TW** [comment]
Hi. I would like to pick this up. Do we want to return the config file in the error message itself? Or do we want to ask and create a sample 1build.yaml file for them in the project directory?

**Comment by gopinath-langote** [comment]
Hello @Ritabrata-TW 
Thanks for opting.

This Issue is related to another Issue: https://github.com/gopinath-langote/1build/issues/84

Which means, help messages showing on this feature is going to depend upon another issue.

It will be good if we play first https://github.com/gopinath-langote/1build/issues/84

WDYT?

**Comment by Ritabrata-TW** [comment]
Sounds good. Will pick up the other issue.

**Comment by gopinath-langote** [comment]
:+1:
